import { test, expect } from '@playwright/test'

async function login(page, username) {
  await page.goto('/login')
  await page.getByLabel('Benutzername').fill(username)
  await page.getByLabel('Passwort', { exact: true }).fill('test-password')
  await page.getByRole('button', { name: 'Anmelden', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Abmelden' })).toBeVisible()
}

test('create, edit, and delete an owned private recipe with parts and photo', async ({ page }) => {
  await login(page, 'alice')
  await page.getByRole('link', { name: '+ Neues Rezept' }).click()
  await page.getByLabel('Rezeptname', { exact: true }).fill('Browser-Testkuchen')
  await page.getByLabel('Öffentlich sichtbar').uncheck()
  await page.getByLabel('Tags hinzufügen').fill('Browser-Privat')
  await page.getByRole('button', { name: 'Tag hinzufügen', exact: true }).click()
  await page.getByRole('combobox', { name: 'Kategorie', exact: true }).selectOption('Nachspeiße')
  await page.getByLabel('Zubereitung', { exact: true }).fill('Zusammensetzen und backen.')
  await page.getByRole('button', { name: '+ Zutat', exact: true }).click()
  await page.getByLabel('Menge', { exact: true }).fill('250')
  await page.getByLabel('Einheit', { exact: true }).fill('g')
  await page.getByLabel('Zutat', { exact: true }).fill('Mehl')
  await page.getByRole('button', { name: '+ Rezeptteil hinzufügen' }).click()
  await page.getByLabel('Name des Teils').fill('Glasur')
  await page.getByLabel('Zubereitung', { exact: true }).nth(1).fill('Schokolade schmelzen.')
  await page.getByRole('button', { name: '+ Rezeptteil hinzufügen' }).click()
  await page.getByLabel('Name des Teils').nth(1).fill('Füllung')
  await page.getByLabel('Zubereitung', { exact: true }).nth(2).fill('Creme aufschlagen.')
  // Small valid PNG; server decoding and conversion are exercised.
  await page.getByLabel('Foto', { exact: true }).setInputFiles({ name: 'photo.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==', 'base64') })
  await page.getByRole('button', { name: 'Rezept speichern' }).click()
  await expect(page).toHaveURL(/\/recipe\/\d+$/)
  const path = new URL(page.url()).pathname
  await expect(page.getByRole('heading', { name: 'Browser-Testkuchen', exact: true }).first()).toBeVisible()
  await expect(page.getByText('🔒 Nur für dich')).toBeVisible()
  await expect(page.getByText('250 g Mehl', { exact: true })).toBeVisible()
  await expect(page.getByText('Schokolade schmelzen.', { exact: true })).toBeVisible()
  await expect(page.getByText('Creme aufschlagen.', { exact: true })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Browser-Testkuchen' })).toBeVisible()
  const imageUrl = await page.getByRole('img', { name: 'Browser-Testkuchen' }).getAttribute('src')
  await expect.poll(() => page.getByRole('img', { name: 'Browser-Testkuchen' }).evaluate(img => img.naturalWidth)).toBeGreaterThan(0)

  await page.getByRole('button', { name: 'Abmelden' }).click()
  await expect(page.getByRole('link', { name: 'Browser-Testkuchen', exact: true })).toHaveCount(0)
  await login(page, 'bob')
  await page.goto(path)
  await expect(page.getByRole('alert')).toContainText('Rezept nicht gefunden')
  const hiddenImage = await page.request.get(imageUrl)
  expect(hiddenImage.status()).toBe(404)

  await page.getByRole('button', { name: 'Abmelden' }).click()
  await login(page, 'alice')
  await page.goto(path)
  await page.getByRole('link', { name: 'Bearbeiten', exact: true }).click()
  await page.getByLabel('Rezeptname', { exact: true }).fill('Browser-Testkuchen geändert')
  await page.getByLabel('Öffentlich sichtbar').check()
  await page.getByRole('button', { name: 'Rezept speichern' }).click()
  await expect(page.getByRole('heading', { name: 'Browser-Testkuchen geändert', exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Abmelden' }).click()
  await page.goto(path)
  await expect(page.getByRole('heading', { name: 'Browser-Testkuchen geändert', exact: true }).first()).toBeVisible()
  await expect(page.getByRole('link', { name: 'Bearbeiten', exact: true })).toHaveCount(0)
  await login(page, 'alice')
  await page.goto(path)
  await page.getByRole('button', { name: 'Löschen', exact: true }).click()
  await page.getByRole('button', { name: 'Ja, löschen', exact: true }).click()
  await expect(page).toHaveURL('/')
  await page.goto(path)
  await expect(page.getByRole('alert')).toContainText('Rezept nicht gefunden')
})

test('Felix edits original public recipes directly on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await login(page, 'felix')
  await page.goto('/recipe/48')
  await expect(page.getByRole('link', { name: 'Rezept kopieren' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Bearbeiten', exact: true }).click()
  await expect(page.getByLabel('Name des Teils').first()).toHaveValue('Pizzateig')
  await expect(page.getByLabel('Portionen des Rezepts')).toHaveValue('4')
  await page.getByRole('combobox', { name: 'Kategorie', exact: true }).selectOption('sonstiges')
  await page.getByLabel('Tags hinzufügen').fill('Familienpizza')
  await page.getByRole('button', { name: 'Tag hinzufügen', exact: true }).click()
  await page.getByRole('button', { name: 'Rezept speichern' }).click()
  await expect(page).toHaveURL('/recipe/48')
  await expect(page.getByRole('heading', { name: 'Pizzateig', exact: true }).first()).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Pizzasoße', exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Abmelden' }).click()
  await page.goto('/recipe/48')
  await expect(page.getByRole('link', { name: 'Familienpizza', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Bearbeiten', exact: true })).toHaveCount(0)
  const photo = page.getByRole('img', { name: 'Pizza', exact: true })
  await expect.poll(() => photo.evaluate(img => img.naturalWidth)).toBeGreaterThan(0)
  const exposed = await page.request.get('/public/data/images/pizza.jpg')
  expect(exposed.status()).toBe(403)
})

test('favourites persist per account and category/tag filters combine', async ({ page }) => {
  await login(page, 'alice')
  await page.goto('/recipe/48')
  await page.getByRole('button', { name: '☆ Zu Favouriten hinzufügen', exact: true }).click()
  await expect(page.getByRole('button', { name: '★ Aus Favouriten entfernen', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '★ Favouriten', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pizza', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Pizza', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Abmelden' }).click()
  await login(page, 'bob')
  await page.getByRole('link', { name: '★ Favouriten', exact: true }).click()
  await expect(page.getByText('Noch keine Favouriten. Markiere ein Rezept mit einem Stern.')).toBeVisible()
  await page.getByRole('link', { name: 'Alle Rezepte', exact: true }).click()
  await page.getByRole('combobox', { name: 'Kategorie', exact: true }).selectOption('Suppe')
  await page.getByRole('checkbox', { name: 'Mama-Rezept', exact: true }).check()
  await expect(page.getByRole('heading', { name: 'Tomatensuppe', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Pizza', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Filter zurücksetzen', exact: true }).click()
  await page.getByRole('button', { name: 'Abmelden' }).click()
  await login(page, 'alice')
  await page.getByRole('link', { name: '★ Favouriten', exact: true }).click()
  await page.getByRole('button', { name: 'Pizza: Aus Favouriten entfernen', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pizza', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Pizza', exact: true })).toHaveCount(0)
})

test('portion controls scale main and part amounts without changing units or saved quantities', async ({ page }) => {
  await login(page, 'alice')
  await page.goto('/new')
  await expect(page.getByLabel('Portionen des Rezepts')).toHaveValue('4')
  await page.getByLabel('Rezeptname', { exact: true }).fill('Portionentest')
  await page.getByRole('button', { name: '+ Zutat', exact: true }).click()
  await page.getByLabel('Menge', { exact: true }).fill('1000')
  await page.getByLabel('Einheit', { exact: true }).fill('g')
  await page.getByLabel('Zutat', { exact: true }).fill('Mehl')
  await page.getByRole('button', { name: '+ Zutat', exact: true }).click()
  await page.getByLabel('Zutat', { exact: true }).nth(1).fill('Salz nach Geschmack')
  await page.getByRole('button', { name: '+ Rezeptteil hinzufügen' }).click()
  await page.getByLabel('Name des Teils').fill('Sauce')
  await page.getByRole('button', { name: '+ Zutat', exact: true }).nth(1).click()
  await page.getByLabel('Menge', { exact: true }).nth(2).fill('0.5')
  await page.getByLabel('Einheit', { exact: true }).nth(2).fill('l')
  await page.getByLabel('Zutat', { exact: true }).nth(2).fill('Milch')
  await page.getByRole('button', { name: 'Rezept speichern' }).click()
  await expect(page).toHaveURL(/\/recipe\/\d+$/)
  const path = new URL(page.url()).pathname
  await page.getByLabel('Portionen', { exact: true }).fill('8')
  await page.getByLabel('Portionen', { exact: true }).press('Tab')
  await expect(page.getByText('2 000 g Mehl', { exact: true })).toBeVisible()
  await expect(page.getByText('1 l Milch', { exact: true })).toBeVisible()
  await expect(page.getByText('Salz nach Geschmack', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Eine Portion weniger', exact: true }).click()
  await expect(page.getByText('1 750 g Mehl', { exact: true })).toBeVisible()
  await expect(page.getByText('0,875 l Milch', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Eine Portion mehr', exact: true }).click()
  await expect(page.getByText('2 000 g Mehl', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Zurück auf 4', exact: true }).click()
  await expect(page.getByText('1 000 g Mehl', { exact: true })).toBeVisible()
  await page.getByLabel('Portionen', { exact: true }).fill('1')
  await page.getByLabel('Portionen', { exact: true }).press('Tab')
  await expect(page.getByRole('button', { name: 'Eine Portion weniger', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByLabel('Portionen', { exact: true })).toHaveValue('4')
  await page.getByRole('link', { name: 'Bearbeiten', exact: true }).click()
  await expect(page.getByLabel('Menge', { exact: true }).first()).toHaveValue('1000')
  await expect(page.getByLabel('Portionen des Rezepts')).toHaveValue('4')
  await page.getByLabel('Portionen des Rezepts').fill('2')
  await page.getByRole('button', { name: 'Rezept speichern' }).click()
  await expect(page.getByLabel('Portionen', { exact: true })).toHaveValue('2')
  await page.getByLabel('Portionen', { exact: true }).fill('4')
  await page.getByLabel('Portionen', { exact: true }).press('Tab')
  await expect(page.getByText('2 000 g Mehl', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Abmelden' }).click()
  await page.goto(path)
  await expect(page.getByLabel('Portionen', { exact: true })).toHaveValue('2')
  await page.getByRole('button', { name: 'Eine Portion mehr', exact: true }).click()
  await expect(page.getByText('1 500 g Mehl', { exact: true })).toBeVisible()
})
