import { test, expect } from '@playwright/test'

async function login(page, username) {
  await page.goto('/login')
  await page.getByLabel('Benutzername').fill(username)
  await page.getByLabel('Passwort', { exact: true }).fill('test-password')
  await page.getByRole('button', { name: 'Anmelden', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Abmelden', includeHidden: true })).toHaveCount(1)
}

async function logout(page) {
  const menu = page.getByRole('button', { name: 'Menü öffnen', exact: true })
  if (await menu.isVisible()) await menu.click()
  await page.getByRole('button', { name: 'Abmelden' }).click()
}

test('create, edit, and delete an owned private recipe with parts and photo', async ({ page }) => {
  await login(page, 'alice')
  await page.getByRole('link', { name: '+ Neues Rezept' }).click()
  await page.getByLabel('Rezeptname', { exact: true }).fill('Browser-Testkuchen')
  await page.getByLabel('Öffentlich sichtbar').uncheck()
  await page.getByLabel('Tags hinzufügen').fill('Browser-Privat')
  await page.getByRole('button', { name: 'Tag hinzufügen', exact: true }).click()
  await page.getByRole('combobox', { name: 'Kategorie', exact: true }).selectOption('Nachspeise')
  await page.getByLabel('Zubereitung', { exact: true }).fill('Zusammensetzen und backen.')
  await page.getByRole('button', { name: '+ Zutat', exact: true }).click()
  await page.getByLabel('Menge', { exact: true }).fill('250')
  await page.getByLabel('Einheit', { exact: true }).fill('g')
  await page.getByLabel('Zutat', { exact: true }).fill('Mehl')
  await page.getByRole('button', { name: '+ Rezeptteil hinzufügen' }).click()
  await page.getByLabel('Name des Teils').fill('Glasur')
  await page.getByLabel('Zubereitung', { exact: true }).nth(1).fill('Schokolade schmelzen.')
  await page.getByRole('button', { name: '+ Rezeptteil hinzufügen' }).click()
  await page.getByLabel('Name des Teils').nth(1).fill('Füllung')
  await page.getByLabel('Zubereitung', { exact: true }).nth(2).fill('Creme aufschlagen.')
  // Small valid PNG; server decoding and conversion are exercised.
  await page.getByLabel('Foto', { exact: true }).setInputFiles({ name: 'photo.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==', 'base64') })
  await page.getByRole('button', { name: 'Rezept speichern' }).click()
  await expect(page).toHaveURL(/\/recipe\/\d+$/)
  const path = new URL(page.url()).pathname
  await expect(page.getByRole('heading', { name: 'Browser-Testkuchen', exact: true }).first()).toBeVisible()
  await expect(page.getByText('🔒 Nur für dich')).toBeVisible()
  await expect(page.getByText('250 g Mehl', { exact: true })).toBeVisible()
  await expect(page.getByText('Schokolade schmelzen.', { exact: true })).toBeVisible()
  await expect(page.getByText('Creme aufschlagen.', { exact: true })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Browser-Testkuchen' })).toBeVisible()
  const imageUrl = await page.getByRole('img', { name: 'Browser-Testkuchen' }).getAttribute('src')
  await expect.poll(() => page.getByRole('img', { name: 'Browser-Testkuchen' }).evaluate(img => img.naturalWidth)).toBeGreaterThan(0)

  await logout(page)
  await expect(page.getByRole('link', { name: 'Browser-Testkuchen', exact: true })).toHaveCount(0)
  await login(page, 'bob')
  await page.goto(path)
  await expect(page.getByRole('alert')).toContainText('Rezept nicht gefunden')
  const hiddenImage = await page.request.get(imageUrl)
  expect(hiddenImage.status()).toBe(404)

  await logout(page)
  await login(page, 'alice')
  await page.goto(path)
  await page.getByRole('link', { name: 'Bearbeiten', exact: true }).click()
  await page.getByLabel('Rezeptname', { exact: true }).fill('Browser-Testkuchen geändert')
  await page.getByLabel('Öffentlich sichtbar').check()
  await page.getByRole('button', { name: 'Rezept speichern' }).click()
  await expect(page.getByRole('heading', { name: 'Browser-Testkuchen geändert', exact: true }).first()).toBeVisible()
  await logout(page)
  await page.goto(path)
  await expect(page.getByRole('heading', { name: 'Browser-Testkuchen geändert', exact: true }).first()).toBeVisible()
  await expect(page.getByRole('link', { name: 'Bearbeiten', exact: true })).toHaveCount(0)
  await login(page, 'alice')
  await page.goto(path)
  await page.getByRole('button', { name: 'Löschen', exact: true }).click()
  await page.getByRole('button', { name: 'Ja, löschen', exact: true }).click()
  await expect(page).toHaveURL('/')
  await page.goto(path)
  await expect(page.getByRole('alert')).toContainText('Rezept nicht gefunden')
})

test('Felix edits original public recipes directly on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await login(page, 'felix')
  await page.goto('/recipe/48')
  await expect(page.getByRole('link', { name: 'Rezept kopieren' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Bearbeiten', exact: true }).click()
  await expect(page.getByLabel('Name des Teils').first()).toHaveValue('Pizzateig')
  await expect(page.getByLabel('Portionen des Rezepts')).toHaveValue('4')
  await page.getByRole('combobox', { name: 'Kategorie', exact: true }).selectOption('sonstiges')
  await page.getByLabel('Tags hinzufügen').fill('Familienpizza')
  await page.getByRole('button', { name: 'Tag hinzufügen', exact: true }).click()
  await page.getByRole('button', { name: 'Rezept speichern' }).click()
  await expect(page).toHaveURL('/recipe/48')
  await expect(page.getByRole('heading', { name: 'Pizzateig', exact: true }).first()).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Pizzasoße', exact: true }).first()).toBeVisible()
  await logout(page)
  await page.goto('/recipe/48')
  await expect(page.getByRole('link', { name: 'Familienpizza', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Bearbeiten', exact: true })).toHaveCount(0)
  const photo = page.getByRole('img', { name: 'Pizza', exact: true })
  await expect.poll(() => photo.evaluate(img => img.naturalWidth)).toBeGreaterThan(0)
  const exposed = await page.request.get('/public/data/images/pizza.jpg')
  expect(exposed.headers()['content-type']).not.toMatch(/^image\//)
})

test('favourites persist per account and category/tag filters combine', async ({ page }) => {
  await login(page, 'alice')
  await page.goto('/recipe/48')
  await page.getByRole('button', { name: 'Zu Favouriten hinzufügen', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Aus Favouriten entfernen', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '★ Favouriten', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pizza', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Pizza', exact: true })).toBeVisible()
  await logout(page)
  await login(page, 'bob')
  await page.getByRole('link', { name: '★ Favouriten', exact: true }).click()
  await expect(page.getByText('Noch keine Favouriten. Markiere ein Rezept mit einem Stern.')).toBeVisible()
  await page.getByRole('link', { name: 'Alle Rezepte', exact: true }).click()
  await page.getByRole('combobox', { name: 'Kategorie', exact: true }).selectOption('Suppe')
  await page.getByRole('checkbox', { name: 'Mama-Rezept', exact: true }).check()
  await expect(page.getByRole('heading', { name: 'Tomatensuppe', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Pizza', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Filter zurücksetzen', exact: true }).click()
  await logout(page)
  await login(page, 'alice')
  await page.getByRole('link', { name: '★ Favouriten', exact: true }).click()
  await page.getByRole('button', { name: 'Pizza: Aus Favouriten entfernen', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pizza', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Pizza', exact: true })).toHaveCount(0)
})

test('portion controls scale main and part amounts without changing units or saved quantities', async ({ page }) => {
  await login(page, 'alice')
  await page.goto('/new')
  await expect(page.getByLabel('Portionen des Rezepts')).toHaveValue('4')
  await page.getByLabel('Rezeptname', { exact: true }).fill('Portionentest')
  await page.getByRole('button', { name: '+ Zutat', exact: true }).click()
  await page.getByLabel('Menge', { exact: true }).fill('1000')
  await page.getByLabel('Einheit', { exact: true }).fill('g')
  await page.getByLabel('Zutat', { exact: true }).fill('Mehl')
  await page.getByRole('button', { name: '+ Zutat', exact: true }).click()
  await page.getByLabel('Zutat', { exact: true }).nth(1).fill('Salz nach Geschmack')
  await page.getByRole('button', { name: '+ Rezeptteil hinzufügen' }).click()
  await page.getByLabel('Name des Teils').fill('Sauce')
  await page.getByRole('button', { name: '+ Zutat', exact: true }).nth(1).click()
  await page.getByLabel('Menge', { exact: true }).nth(2).fill('0.5')
  await page.getByLabel('Einheit', { exact: true }).nth(2).fill('l')
  await page.getByLabel('Zutat', { exact: true }).nth(2).fill('Milch')
  await page.getByRole('button', { name: 'Rezept speichern' }).click()
  await expect(page).toHaveURL(/\/recipe\/\d+$/)
  const path = new URL(page.url()).pathname
  await page.getByLabel('Portionen', { exact: true }).fill('8')
  await page.getByLabel('Portionen', { exact: true }).press('Tab')
  await expect(page.getByText('2 000 g Mehl', { exact: true })).toBeVisible()
  await expect(page.getByText('1 l Milch', { exact: true })).toBeVisible()
  await expect(page.getByText('Salz nach Geschmack', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Eine Portion weniger', exact: true }).click()
  await expect(page.getByText('1 750 g Mehl', { exact: true })).toBeVisible()
  await expect(page.getByText('0,875 l Milch', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Eine Portion mehr', exact: true }).click()
  await expect(page.getByText('2 000 g Mehl', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Zurück auf 4', exact: true })).toHaveCount(0)
  await page.getByLabel('Portionen', { exact: true }).fill('4')
  await page.getByLabel('Portionen', { exact: true }).press('Tab')
  await expect(page.getByText('1 000 g Mehl', { exact: true })).toBeVisible()
  await page.getByLabel('Portionen', { exact: true }).fill('1')
  await page.getByLabel('Portionen', { exact: true }).press('Tab')
  await expect(page.getByRole('button', { name: 'Eine Portion weniger', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByLabel('Portionen', { exact: true })).toHaveValue('4')
  await page.getByRole('link', { name: 'Bearbeiten', exact: true }).click()
  await expect(page.getByLabel('Menge', { exact: true }).first()).toHaveValue('1000')
  await expect(page.getByLabel('Portionen des Rezepts')).toHaveValue('4')
  await page.getByLabel('Portionen des Rezepts').fill('2')
  await page.getByRole('button', { name: 'Rezept speichern' }).click()
  await expect(page.getByLabel('Portionen', { exact: true })).toHaveValue('2')
  await page.getByLabel('Portionen', { exact: true }).fill('4')
  await page.getByLabel('Portionen', { exact: true }).press('Tab')
  await expect(page.getByText('2 000 g Mehl', { exact: true })).toBeVisible()
  await logout(page)
  await page.goto(path)
  await expect(page.getByLabel('Portionen', { exact: true })).toHaveValue('2')
  await page.getByRole('button', { name: 'Eine Portion mehr', exact: true }).click()
  await expect(page.getByText('1 500 g Mehl', { exact: true })).toBeVisible()
})


test('registration creates a shared account and signs in immediately', async ({ page }) => {
  await page.goto('/login?next=/favourites')
  await page.getByRole('link', { name: 'Registrieren', exact: true }).last().click()
  await page.getByLabel('Benutzername').fill('browser.family')
  await page.getByLabel('Passwort', { exact: true }).fill('family-password')
  await page.getByLabel('Passwort wiederholen').fill('different-password')
  await page.getByRole('button', { name: 'Registrieren', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('stimmen nicht überein')
  await page.getByLabel('Passwort wiederholen').fill('family-password')
  await page.getByRole('button', { name: 'Registrieren', exact: true }).click()
  await expect(page).toHaveURL('/favourites')
  await expect(page.getByRole('button', { name: 'Abmelden', includeHidden: true })).toHaveCount(1)
  await logout(page)
  await page.goto('/register')
  await page.getByLabel('Benutzername').fill('browser.family')
  await page.getByLabel('Passwort', { exact: true }).fill('family-password')
  await page.getByLabel('Passwort wiederholen').fill('family-password')
  await page.getByRole('button', { name: 'Registrieren', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('bereits vergeben')
})

test('desktop filters stay left and sticky; stars and detail metadata are compact', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 900 })
  await login(page, 'felix')
  const ids = []
  try {
    for (let i = 0; i < 18; i++) {
      const response = await page.request.post('/api/recipes/', { headers: { Origin: 'http://localhost:15173' }, data: { title: `Sidebar ${i}`, category: 'Hauptspeise', tags: ['Sidebar'], instructions: '' } })
      expect(response.status()).toBe(201)
      ids.push((await response.json()).id)
    }
    await page.goto('/')
    await expect(page.locator('.recipe-card').first()).toBeVisible()
    await expect(page.locator('.recipe-card .category-badge, .recipe-card .recipe-tags')).toHaveCount(0)
    const sidebar = page.locator('.recipe-filters')
    expect((await sidebar.boundingBox()).x).toBeLessThanOrEqual(20)
    expect((await page.locator('.recipe-grid').boundingBox()).width).toBeGreaterThan(1200)
    await page.screenshot({ path: 'test-results/recipes-desktop.png' })
    expect((await sidebar.boundingBox()).x).toBeLessThan((await page.locator('.recipe-grid').boundingBox()).x)
    await page.evaluate(() => window.scrollTo(0, 350))
    expect((await sidebar.boundingBox()).y).toBeCloseTo(16, 0)
    await page.goto('/recipe/48')
    const star = page.getByRole('button', { name: 'Zu Favouriten hinzufügen', exact: true })
    await expect(star).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(star.locator('svg')).toBeVisible()
    await star.click()
    await expect(page.getByRole('button', { name: 'Aus Favouriten entfernen', exact: true })).toHaveCSS('color', 'rgb(234, 179, 8)')
    const title = await page.locator('.recipe-heading h1').boundingBox()
    const edit = await page.getByRole('link', { name: 'Bearbeiten', exact: true }).boundingBox()
    expect(Math.abs(title.y - edit.y)).toBeLessThan(25)
    const meta = page.locator('.recipe-meta')
    expect(Math.abs((await meta.locator('.category-badge').boundingBox()).y - (await meta.locator('.tag').first().boundingBox()).y)).toBeLessThan(10)
    await page.getByRole('button', { name: 'Aus Favouriten entfernen', exact: true }).click()
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/')
    await expect(page.locator('.recipe-card').first()).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: 'test-results/recipes-mobile.png', fullPage: true })
  } finally {
    for (const id of ids) await page.request.delete(`/api/recipes/${id}`, { headers: { Origin: 'http://localhost:15173' } })
  }
})


test('mobile navigation uses one header row and closes on navigation, Escape and outside clicks', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const nav = page.getByRole('navigation', { name: 'Hauptnavigation', includeHidden: true })
  await expect(nav).toBeHidden()
  await page.getByRole('button', { name: 'Menü öffnen' }).click()
  await expect(nav).toBeVisible()
  await expect(page.getByRole('button', { name: 'Menü schließen' })).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('link', { name: 'Anmelden', exact: true }).click()
  await expect(page).toHaveURL('/login')
  await expect(nav).toBeHidden()
  await login(page, 'felix')
  for (const width of [320, 390, 768]) {
    await page.setViewportSize({ width, height: 844 })
    expect((await page.locator('.header').boundingBox()).height).toBeLessThanOrEqual(80)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'Menü öffnen' }).click()
    await expect(page.getByRole('link', { name: '★ Favouriten', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(nav).toBeHidden()
    await expect(page.getByRole('button', { name: 'Menü öffnen' })).toBeFocused()
  }
  await page.getByRole('button', { name: 'Menü öffnen' }).click()
  await page.locator('.page-heading h2').click()
  await expect(nav).toBeHidden()
  await page.getByRole('button', { name: 'Menü öffnen' }).click()
  await page.getByRole('link', { name: '★ Favouriten', exact: true }).click()
  await expect(page).toHaveURL('/favourites')
  await expect(nav).toBeHidden()
  await page.getByRole('button', { name: 'Menü öffnen' }).click()
  await page.screenshot({ path: 'test-results/mobile-menu.png' })
  await logout(page)
  await expect(nav).toBeHidden()
  await page.getByRole('button', { name: 'Menü öffnen' }).click()
  await expect(page.getByRole('link', { name: 'Registrieren', exact: true })).toBeVisible()
})
